name: My First GitHub Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   #using ready made tool to copy code
      - run: echo "Code checked out!" #you manually running a command
  
