name: My First GitHub Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_PROJECT: langgraph-eval-project-new
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v3
        # copy code
      - uses: actions/setup-python@v4
        # install python
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
        # install libraries
      - run: pytest test_backend.py -v   # ← add this line!
      - run: echo "All done!"